export const FOOTER_SLOGAN = "🚀 Build Your Professional Resume in Minutes"
export const FOOTER_P_TAG = "**Privacy First:** Your data stays with you! We are a simple, privacy-focused tool designed to help you generate a polished resume quickly. ** We do not store any of your personal information** "
export const FOOTER_COPYRIGHT_TEXT = `© ${new Date().getFullYear()} Resume Builder | Qpkendra`;
export const FOOTER_GOOGLE_TAG_NOTICE = "**Note:** This site uses **Google Analytics** to gather anonymous usage data to improve our service."
export const FOOTER_DISCLAIMER = "We do not store any personal data with QPKendra. We are not responsible for any suggestions or content generated by the user."
export const SAMPLE_JSON_DATA = {
    "fullName": "Alex Sterling",
    "jobTitle": "Senior Frontend Engineer | React.js | Next.js | TypeScript",
    "location": "Austin, Texas",
    "phone": "+1 (512) 555-0198",
    "email": "alex.sterling.dev@example.com",
    "github": "https://github.com/alexsterling",
    "linkedin": "https://linkedin.com/in/alexsterling",
    "portfolio": "https://alexsterling.dev",
    "summary": "Senior Frontend Engineer with 4+ years of experience in architecting scalable, high-performance web applications. Expert in React.js and Next.js, with a strong focus on UI/UX, performance optimization, and accessibility.",
    "GENERATED_BY": "https://resume-builder.qpkendra.com",
    "skills": [
        {
            "id": 1,
            "category": "Core & Frameworks",
            "items": "React.js, Next.js (SSR/SSG), TypeScript, JavaScript (ES6+), Micro Frontends, System Design"
        },
        {
            "id": 2,
            "category": "State & Data",
            "items": "Redux Toolkit, GraphQL, Apollo Client, Context API, REST API Integration"
        },
        {
            "id": 3,
            "category": "Styling & UI",
            "items": "Tailwind CSS, Material UI, Design Systems, Responsive Design, Accessibility (A11y)"
        }
    ],
    "experience": [
        {
            "id": 1,
            "company": "Global Tech Solutions Inc.",
            "role": "Lead Frontend Consultant",
            "duration": "Jan 2022 – Present",
            "location": "Austin, TX (Remote)",
            "clients": [
                {
                    "id": 1765133426476,
                    "name": "HealthTech Systems Corp",
                    "bulletPoints": [
                        "**Data Visualization Engine**: Orchestrated the integration of complex analytics into **React.js** applications, delivering real-time interactive dashboards for medical stakeholders.",
                        "**Workflow Automation**: Streamlined clinical reporting by architecting custom API connectors and automated flows, reducing manual data processing time by **40%**.",
                        "**Performance Tuning**: Optimized render cycles and state management, achieving a **30% improvement** in page load speed for high-traffic patient portals."
                    ]
                },
                {
                    "id": 1774976308818,
                    "name": "FinTech Innovations Ltd",
                    "bulletPoints": [
                        "**Financial Application Development**: Developed a high-performance **React.js** application for financial operations, focusing on real-time data accuracy and secure transaction workflows.",
                        "**Security Compliance**: Collaborated with security teams to implement robust authentication and authorization protocols, ensuring full **GDPR & SOC2** compliance."
                    ]
                }
            ]
        }
    ],
    "education": [
        {
            "id": 1,
            "degree": "B.S. in Computer Science",
            "institution": "University of Texas at Austin",
            "duration": "2016–2020",
            "location": "Austin, TX",
            "gpaLabel": "CGPA",
            "gpaValue": "3.8/4.0"
        }
    ],
    "projects": [
        {
            "id": 1,
            "name": "EduMetric | edumetric-platform.io",
            "icon": "💻",
            "tech": "React.js, Node.js, SEO Optimization",
            "description": "Designed and developed an academic analytics platform with **20M+ lifetime views**. Built scalable React.js UI and optimized performance for high-traffic content delivery.",
            "link": "https://edumetric-platform.io"
        },
        {
            "id": 2,
            "name": "SwiftSwift API Finder",
            "icon": "",
            "tech": "Next.js 14, SSG, TypeScript",
            "description": "Developed a high-performance directory using **Static Site Generation (SSG)** to handle thousands of pages with near-instant load times. Achieved perfect Lighthouse scores.",
            "link": "https://swift-api-finder.io"
        }
    ],
    "certifications": [
        {
            "id": 1,
            "name": "AWS Certified Solutions Architect",
            "issuer": "Amazon Web Services",
            "expiryDate": "Never Expires",
            "credentialId": "AWS-123456789",
            "link": "https://credly.com/aws-cert"
        },
        {
            "id": 2,
            "name": "Meta Front-End Developer Professional Certificate",
            "issuer": "Meta",
            "expiryDate": "2025",
            "credentialId": "META-CERT-7788",
            "link": "https://coursera.org/verify/meta"
        }
    ],
    "achievements": [
        "Recipient of the **Golden Pixel Award** for Excellence in UI/UX Design (2023).",
        "Mentored **10+ junior developers**, helping them transition into senior roles within 18 months.",
        "Authored a technical whitepaper on **Micro Frontends** with over 5,000 shares on LinkedIn."
    ],
    "storageType": "persistent",
    "themeMode": "light",
    "atsMode": false,
    "themeColor": "#0f172a",
    "selectedTemplate": "template-1",
    "fontFamily": "Default"
}
