export const FOOTER_SLOGAN="🚀 Build Your Professional Resume in Minutes"
export const FOOTER_P_TAG="**Privacy First:** Your data stays with you! We are a simple, privacy-focused tool designed to help you generate a polished resume quickly. ** We do not store any of your personal information** "
export const FOOTER_COPYRIGHT_TEXT = `© ${new Date().getFullYear()} Resume Builder | Qpkendra`;
export const FOOTER_GOOGLE_TAG_NOTICE="**Note:** This site uses **Google Analytics** to gather anonymous usage data to improve our service."
export const FOOTER_DISCLAIMER="We do not store any personal data with QPKendra. We are not responsible for any suggestions or content generated by the user."
export const SAMPLE_JSON_DATA = {
    "fullName": "Jane Doe",
    "jobTitle": "Senior Frontend Engineer | Vue.js | AWS | UI/UX Enthusiast",
    "location": "Bangalore, India",
    "phone": "+91 9876543210",
    "email": "janedoe.dev@example.com",
    "github": "github.com/janedoe-code",
    "summary": "Results-oriented Senior Software Engineer with 6+ years of experience specializing in modern frontend architectures and cloud-native applications. Proficient in Vue.js, TypeScript, and AWS serverless technologies. ** Proven track record of leading teams in the fintech and e-commerce sectors, optimizing page load times by 40%**, and designing accessible, responsive user interfaces.",
    "GENERATED_BY":"https://resume-builder.qpkendra.com",
    "skills": [
        {
            "id": 1,
            "category": "Frontend",
            "items": "Vue.js, Nuxt.js, TypeScript, Tailwind CSS, SASS, Webpack"
        },
        {
            "id": 2,
            "category": "Backend",
            "items": "Python, Django, PostgreSQL, GraphQL"
        },
        {
            "id": 3,
            "category": "Cloud & DevOps",
            "items": "AWS (Lambda, S3, DynamoDB), Docker, Kubernetes, Terraform"
        }
    ],
    "experience": [
        {
            "id": 1,
            "company": "TechFlow Solutions",
            "role": "Senior Software Engineer",
            "duration": "Mar 2022 - Present",
            "clients": [
                {
                    "id": 1765822982114,
                    "name": "Global Fintech Alliance",
                    "bulletPoints": [
                        "Architected a **micro-frontend architecture using Vue.js and Module Federation**, reducing deployment times by 60%.",
                        "Implemented secure authentication flows using OAuth2 and AWS Cognito for a user base of 500k+."
                    ]
                }
            ]
        }
    ],
    "education": [
        {
            "id": 1,
            "degree": "M.S. in Computer Science",
            "institution": "Indian Institute of Technology (IIT), Delhi",
            "duration": "2017-2019"
        },
        {
            "id": 2,
            "degree": "B.E. in Information Technology",
            "institution": "Anna University, Chennai",
            "duration": "2013-2017"
        }
    ],
    "projects": [
        {
            "id": 1,
            "name": "TaskMaster Pro",
            "icon": "✅",
            "tech": "Vue 3, Pinia, Firebase",
            "description": "A collaborative project management tool with **real-time updates and drag-and-drop Kanban boards.**"
        },
        {
            "id": 2,
            "name": "CryptoWatch",
            "icon": "📈",
            "tech": "React Native, CoinGecko API",
            "description": "Cross-platform **mobile application** for tracking cryptocurrency prices and setting custom alerts."
        }
    ],
    "certifications": [
        {
            "id": 1,
            "name": "AWS Certified Solutions Architect - Associate",
            "expiryDate": "2027-08-15"
        },
        {
            "id": 2,
            "name": "Certified Kubernetes Administrator (CKA)",
            "expiryDate": "2027-08-15"
        }
    ]
}