export const FOOTER_SLOGAN = "🚀 Build Your Professional Resume in Minutes"
export const FOOTER_P_TAG = "**Privacy First:** Your data stays with you! We are a simple, privacy-focused tool designed to help you generate a polished resume quickly. ** We do not store any of your personal information** "
export const FOOTER_COPYRIGHT_TEXT = `© ${new Date().getFullYear()} Resume Builder | Qpkendra`;
export const FOOTER_GOOGLE_TAG_NOTICE = "**Note:** This site uses **Google Analytics** to gather anonymous usage data to improve our service."
export const FOOTER_DISCLAIMER = "We do not store any personal data with QPKendra. We are not responsible for any suggestions or content generated by the user."
export const SAMPLE_JSON_DATA = {
    "fullName": "Alex Sterling",
    "jobTitle": "Senior Frontend Engineer | React.js | Next.js | TypeScript",
    "location": "Austin, Texas",
    "phone": "+1 (512) 555-0198",
    "email": "alex.sterling.dev@example.com",
    "github": "://github.com",
    "summary": "Senior Frontend Engineer with 4+ years of experience in architecting scalable, high-performance web applications.",
    "GENERATED_BY": "https://resume-builder.qpkendra.com",
    "skills": [
        {
            "id": 1,
            "category": "Core & Frameworks",
            "items": "React.js, Next.js (SSR/SSG), TypeScript, JavaScript (ES6+), Micro Frontends, System Design"
        },
        {
            "id": 2,
            "category": "State & Data",
            "items": "Redux Toolkit, GraphQL, Apollo Client, Context API, REST API Integration"
        },
        {
            "id": 3,
            "category": "Styling & UI",
            "items": "Tailwind CSS, Material UI, Design Systems, Responsive Design, Accessibility (A11y)"
        }
    ],
    "experience": [
        {
            "id": 1,
            "company": "Global Tech Solutions Inc.",
            "role": "Lead Frontend Consultant",
            "duration": "Jan 2022 – Present",
            "clients": [
                {
                    "id": 1765133426476,
                    "name": "HealthTech Systems Corp",
                    "bulletPoints": [
                        "**Data Visualization Engine**: Orchestrated the integration of complex analytics into **React.js** applications, delivering real-time interactive dashboards for medical stakeholders.",
                        "**Workflow Automation**: Streamlined clinical reporting by architecting custom API connectors and automated flows, reducing manual data processing time by **40%**.",
                    ]
                },
                {
                    "id": 1774976308818,
                    "name": "FinTech Innovations Ltd",
                    "bulletPoints": [
                        "**Financial Application Development**: Developed a high-performance **React.js** application for financial operations, focusing on real-time data accuracy and secure transaction workflows.",
                    ]
                }
            ]
        }
    ],
    "education": [
        {
            "id": 1,
            "degree": "B.S. in Computer Science",
            "institution": "University of Texas at Austin",
            "duration": "2016–2020"
        }
    ],
    "projects": [
        {
            "id": 1,
            "name": "EduMetric | edumetric-platform.io",
            "icon": "💻",
            "tech": "React.js, Node.js, SEO Optimization",
            "description": "Designed and developed an academic analytics platform with **20M+ lifetime views**. Built scalable React.js UI and optimized performance for high-traffic content delivery.",
            "link": "edumetric-platform.io"
        },
        {
            "id": 2,
            "name": "SwiftSwift API Finder",
            "icon": "💳",
            "tech": "Next.js 14, SSG, TypeScript",
            "description": "Developed a high-performance directory using **Static Site Generation (SSG)** to handle thousands of pages with near-instant load times. Achieved perfect Lighthouse scores.",
            "link": "swift-api-finder.io"
        }
    ],
    "certifications": [
        {
            "id": 1,
            "name": "AWS Certified Solutions Architect"
        },
        {
            "id": 2,
            "name": "Meta Front-End Developer Professional Certificate"
        }
    ],
    "storageType": "persistent",
    "themeMode": "dark",
    "atsMode": true,
    "themeColor": "#334155",
    "selectedTemplate": "template-2",
    "fontFamily": "Default"
}
