import { FOOTER_COPYRIGHT_TEXT, FOOTER_GOOGLE_TAG_NOTICE, FOOTER_P_TAG, FOOTER_SLOGAN } from "./V4/components/utils/constat";
import { processTextFormatting } from "./V4/components/utils/dataHelper";

const Footer = () => {
  return (
    <footer className="bg-gray-800 text-white p-4 mt-6 footer-block">
      <div className="container mx-auto flex flex-col items-center ">
        
        {/* === Webpage Note (New Section) === */}
        <div className="text-center mb-2 pb-4 border-b border-gray-700 w-full max-w-2xl">
          <h3 className="text-xl font-semibold text-teal-300 mb-1" dangerouslySetInnerHTML={{ __html: processTextFormatting(FOOTER_SLOGAN) }}/>
           
          <p className="text-[10px] text-gray-300 border-b  border-gray-700 w-full max-w-2xl" dangerouslySetInnerHTML={{ __html: processTextFormatting(FOOTER_P_TAG) }}/>
          <p className="text-[10px] text-gray-300" dangerouslySetInnerHTML={{ __html: processTextFormatting(FOOTER_GOOGLE_TAG_NOTICE) }}/>
            
        </div>

        {/* === Copyright & Disclaimer Section === */}
        <div className="flex flex-col sm:flex-row justify-between items-center w-full max-w-2xl text-center sm:text-left">
          
          {/* Copyright */}
          <p className="text-sm mb-2 sm:mb-0" dangerouslySetInnerHTML={{ __html: processTextFormatting(FOOTER_COPYRIGHT_TEXT) }}/>
            {/* &copy; {new Date().getFullYear()} **Resume Builder | Qpkendra** */}
         

          {/* Disclaimer */}
          <p className="text-[10px] text-gray-400 max-w-sm sm:max-w-xs">
            We do not store any personal data with QPKendra. We are not responsible for any suggestions or content generated by the user.
          </p>
        </div>
        
      </div>
    </footer>
  );
};

export default Footer;